# Generated by Django 4.1.13 on 2024-01-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_rename_video_file_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='subtitles',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.TextField(),
        ),
    ]
